SG-8048: App with devtools
shotgunsoftware/tk-multi-devutils pull request #1
Opened 2018-08-09 03:39 UTC by manneohrstrom

Adds new developer options as context menu actions:

![image](https://user-images.githubusercontent.com/337710/43876623-ebe778d0-9bd0-11e8-8add-2832924c55e1.png)

These appear dynamically depending on your config.

- if you are on a centralized config, nothing appears
- if you are on a distributed non-dev (e.g. zipped) config, you get the option to create a config sandbox.
- once you go into the dev sandbox (e.g. configs with dev descriptor), you get two additional options that let you show the config in the file system as well as run `tank updates` on it.

The create dev sandbox dialog looks like this:
![image](https://user-images.githubusercontent.com/337710/43876739-5ca051c8-9bd1-11e8-87f7-eb5a081375c3.png)

The check for updates looks like this:
![image](https://user-images.githubusercontent.com/337710/43876719-466d2d4a-9bd1-11e8-86a3-6617fe627850.png)

2018-09-24 13:15 UTC, jfboismenu requested changes
This app is going to be so useful for our users. I'm really happy with the workflow.

I am concerned with some of the implementation details however like the reliance on some private APIs and redirecting stdout/stdin instead of passing callbacks to the core.

2018-09-24 13:15 UTC, jfboismenu commented on app.py
> +        pipeline_config_id = self.sgtk.pipeline_configuration.get_shotgun_id()
You are accessing a private api here. We should find a way to make this public.

2018-09-24 13:15 UTC, jfboismenu commented on app.py
> +        if sg_data and (sg_data["windows_path"] or sg_data["mac_path"] or sg_data["linux_path"]):
Could you make sure that is indeed the case? I'm pretty sure we also support the _path fields when using a plugin id. Not sure what it means tough. Anyhow, my point is that we have a method on the Toolkit instance that allows us to know if the configuration is centralized or not, so the logic is encapsulated there, but also because there's some confusion (I might be the one being confused actually!) over what constitutes as a centralized config.

2018-09-24 13:15 UTC, jfboismenu commented on app.py
> +        if sg_data and (sg_data["windows_path"] or sg_data["mac_path"] or sg_data["linux_path"]):
I just looked and there seems to be an [oversight](https://github.com/shotgunsoftware/tk-core/blob/master/python/tank/bootstrap/resolver.py#L375-L398).

We're assuming that if there is a path that a configuration is always centralized. I don't have a problem with that if we really want that to be the case. But then at the very least we should detect the error if both the path AND the plugin id set. We should log and skip it basically.

2018-09-24 13:15 UTC, jfboismenu commented on app.py
> +        if self.sgtk.configuration_descriptor.is_dev():
What is the difference between a dev and a path descriptor? I'm personally always using a path descriptor. Is that distinction really useful? Should we fold the concepts together?

2018-09-24 13:15 UTC, jfboismenu commented on app.py
> +        if sys.platform.startswith("linux"):
This is a pattern that I've seen reproduced quite often and we should stop propagating it.

Could you please introduce a method in core that does the following:

```
def open_file(path):
    try:
        from sgtk.platform.qt import QDesktopServices
    except ImportError:
        # Do that logic you just typed
    else:
        QDesktopServices.openUrl(path)
```

Qt already has this logic built-in

2018-09-24 13:15 UTC, jfboismenu commented on info.yml
> +requires_core_version: "v0.18.122"
We'll want to bump this version number after we introduce the changes I've suggested to core.

2018-09-24 13:15 UTC, jfboismenu commented on python/__init__.py
> +from . import check_updates
W00f (I'm going to pretend I'm Hound CI). Missing end of file CR.

2018-09-24 13:15 UTC, jfboismenu commented on python/check_updates/__init__.py
> +
Woof. Emtpy lines at the end of the file.

2018-09-24 13:15 UTC, jfboismenu commented on python/check_updates/dialog.py
> +        if "[Yna?]" in self._previous_stdout_stderr_line:
I don't get this. Are you saying that we are capturing stdout and popping message boxes to ask for yes/no/all?

It feels like we should instead have a callback that you can pass to the interactive command that receives in the question and the list of choices you can make. Then we built a UI and return the result. The default implementation would simply use stdin. Parsing stdout seems like we're going to break this at some point.

2018-09-24 13:15 UTC, jfboismenu commented on python/check_updates/redirect.py
> +import sys
All this complexity would go away if we simply passed in a callback to the command tank command.

2018-09-24 13:15 UTC, jfboismenu commented on python/check_updates/yes_no_dialog.py
> +from sgtk.platform.qt import QtCore, QtGui
Without a screenshot, it's hard to tell what is the difference here between this and a QMessageBox, especially since QMesssageBox supports a Yes/No/Yes to All. If even supports buttons with custom labels if you really want to use `Always` as a caption.

Could we use a simple QMessageBox?

2018-09-24 13:15 UTC, jfboismenu commented on python/create_sandbox/__init__.py
> +
Woof. Empty lines.

2018-09-24 13:15 UTC, jfboismenu commented on python/create_sandbox/dialog.py
> +                sgtk.util.filesystem.safe_delete_folder(
Should this be part of the copy?

2018-09-24 13:15 UTC, jfboismenu commented on python/create_sandbox/dialog.py
> +                [["id", "is", self._bundle.sgtk.pipeline_configuration.get_shotgun_id()]],
Access to private API.

2018-09-24 13:15 UTC, jfboismenu commented on python/create_sandbox/dialog.py
> +                [["id", "is", self._bundle.sgtk.pipeline_configuration.get_shotgun_id()]],
Maybe we need `self._bundle.sgtk.get_pipeline_configuration_entity()` which returns a dict with keys `name`, `plugin_id`, `descriptor`, `*_path` and does the massaging to we don't have to deal with sg_plugin_ids vs plugin_ids and sg_description vs descriptor.

Emphasis on the `_entity` bit in case in the future we decide to have an actual pipeline configuration object in the public API.

2018-09-24 13:15 UTC, jfboismenu commented on python/create_sandbox/dialog.py
> +            descriptor_uri = "sgtk:descriptor:dev?path=%s" % urllib.quote(path)
Shouldn't we set the platform's field instead of the general path field? Setting the platform field would give a
"This descriptor is not configured for this current OS." like error in the resolver instead of "Path does not exists."

2018-09-24 13:15 UTC, jfboismenu commented on python/create_sandbox/dialog.py
> +            sg_data = self._bundle.shotgun.create(
We should make it clear at this point that the sandbox has been created, but that we haven't switched to it and that the user needs to restart the DCC or exit and reenter their project in Desktop.

2018-09-24 13:15 UTC, jfboismenu commented on resources/create_sandbox/build_resources.sh
> +PYTHON_BASE="/Applications/Shotgun.app/Contents/Resources/Python/bin"
I would so love to refactor this piece of logic into a tk-build python module or something....

2018-09-24 13:17 UTC, jfboismenu commented on python/create_sandbox/dialog.py
> +        self.ui.copy_config.setChecked(False)
I think that checkbox should probably on by default. If you are creating a sandbox, it's usually to tweak things.

2018-09-25 13:28 UTC, manneohrstrom commented on app.py
> +        if sys.platform.startswith("linux"):
yes, it's duplicated in a bunch of places. I'll sort it out as part of my changes to core in the other PR.

2018-09-25 13:33 UTC, manneohrstrom commented on app.py
> +        pipeline_config_id = self.sgtk.pipeline_configuration.get_shotgun_id()
yes, let's discuss this. Maybe we need to make `pipeline_configuration` official?

2018-09-25 13:35 UTC, manneohrstrom commented on app.py
> +        if self.sgtk.configuration_descriptor.is_dev():
We used to have a dev descriptor only - intended for development only! then people started to use it to describe paths on disk to stuff for use in non-dev situations, so we added a path descriptor in 0.18. I think it makes sense to have both, it's useful to be able to say "when in dev mode, do this" - like this in this example. You should switch to using dev descriptors for your development work :)

2018-09-25 13:35 UTC, manneohrstrom commented on info.yml
> +requires_core_version: "v0.18.122"
good point!

2018-09-25 13:38 UTC, manneohrstrom commented on python/check_updates/dialog.py
> +        if "[Yna?]" in self._previous_stdout_stderr_line:
Let's discuss the pragmatic way forward here - these prompts are generated by a [standard set of methods](https://github.com/shotgunsoftware/tk-core/blob/master/python/tank/commands/console_utils.py#L45) in core so it's not random. But yes, we are parsing stdout.

2018-09-25 13:39 UTC, manneohrstrom commented on python/create_sandbox/dialog.py
> +            descriptor_uri = "sgtk:descriptor:dev?path=%s" % urllib.quote(path)
cool idea!

2018-09-25 13:40 UTC, manneohrstrom commented on resources/create_sandbox/build_resources.sh
> +PYTHON_BASE="/Applications/Shotgun.app/Contents/Resources/Python/bin"
oh yes!

2018-09-25 14:41 UTC, jfboismenu commented on python/check_updates/dialog.py
> +        if "[Yna?]" in self._previous_stdout_stderr_line:
Which are not unit tested, so we can break this. ;)

I simply feel that the number of lines of code to use callbacks in core is going to much lower than the number of lines in your app to capture and write text. Callbacks are going to be easier to maintain and easier to understand and not prone to breakage if we change what text is output.

2018-10-04 16:35 UTC, manneohrstrom commented on app.py
> +        if sys.platform.startswith("linux"):
done. in 18.156

2018-10-04 16:36 UTC, manneohrstrom commented on resources/create_sandbox/build_resources.sh
> +PYTHON_BASE="/Applications/Shotgun.app/Contents/Resources/Python/bin"
FYI i have created a separate ticket for this work.

2018-10-04 16:38 UTC, manneohrstrom commented on python/create_sandbox/dialog.py
> +        self.ui.copy_config.setChecked(False)
see logic below. if the folder specified contains any files, the checkbox gets unticked, otherwise it is ticked. The rationale is that if there is stuff already there in the location we are setting up, we default to not copy. If the folder is empty, we default to copy.

2018-10-04 17:23 UTC, manneohrstrom commented on python/create_sandbox/dialog.py
> +            sg_data = self._bundle.shotgun.create(
it currently says:

![image](https://user-images.githubusercontent.com/337710/46491401-8f08ab80-c802-11e8-9482-c7bdf7390f2e.png)

2018-10-08 10:07 UTC, manneohrstrom commented
Ready for another round of review. Based on your feedback, refactored the interaction with the tank command (FWIW, turned this into a much bigger chunk of work) and added explicit methods to core rather than accessing `pipeline_configuration`.

2018-10-08 10:08 UTC, manneohrstrom commented on app.py
> +        if self.sgtk.configuration_mode != self.sgtk.DISTRIBUTED:
logic for determining the config mode is now in core.

2018-10-08 10:08 UTC, manneohrstrom commented on app.py
> +        command_runner = self.import_module("command_runner")
turned updates ui into a generic tank command runner.

2018-10-08 10:09 UTC, manneohrstrom commented on info.yml
> +requires_core_version: "v0.18.156"
i will bump this later on.

2018-10-08 10:09 UTC, manneohrstrom commented on python/command_runner/dialog.py
> +        self._interaction_interface = QtInteraction(self)
new interface for interacting with tank commands

2018-10-08 10:09 UTC, manneohrstrom commented on python/command_runner/dialog.py
> +            self._command_obj.terminate()
new method for requesting a termination of tank commands.

2018-10-08 10:10 UTC, manneohrstrom commented on python/create_sandbox/dialog.py
> +                [["id", "is", self._bundle.sgtk.configuration_id]],
new property in core.

2018-10-09 13:33 UTC, jfboismenu approved these changes
🚢 :shipit: 

Awesome work! I'm looking forward to using it myself.

2018-10-09 14:01 UTC, merged